#!/usr/bin/env python3
"""
HN News Digest Agent
Scrapes HackerNews frontpage, filters by keywords, sends daily curated tech news digest.
"""

import json
import re
from datetime import datetime
from typing import List, Dict, Optional

try:
    import requests
except ImportError:
    print("requests library not available, using urllib")
    import urllib.request
    requests = None

# Configuration
HN_API_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
HN_ITEM_URL = "https://hacker-news.firebaseio.com/v0/item/{}.json"
HN_FRONT_PAGE = "https://news.ycombinator.com"

# Keywords for filtering tech news
KEYWORDS = [
    "ai", "machine learning", "llm", "gpt", "neural", "openai",
    "python", "javascript", "typescript", "rust", "golang", "java",
    "kubernetes", "docker", "cloud", "aws", "azure", "gcp",
    "security", "vulnerability", "exploit", "privacy",
    "startup", "funding", "acquisition", "ipo",
    "developer", "programming", "framework", "library",
    "open source", "github", "linux", "kernel",
    "api", "database", "postgres", "mysql", "mongodb",
    "web", "browser", "frontend", "backend", "fullstack",
    "mobile", "ios", "android", "react", "node",
]

def fetch_hn_top_stories(limit: int = 30) -> List[int]:
    """Fetch top story IDs from HN API."""
    if requests:
        response = requests.get(HN_API_URL, timeout=10)
        response.raise_for_status()
        return response.json()[:limit]
    else:
        with urllib.request.urlopen(HN_API_URL, timeout=10) as resp:
            data = json.loads(resp.read().decode())
            return data[:limit]

def fetch_story_details(story_id: int) -> Optional[Dict]:
    """Fetch details for a single story."""
    url = HN_ITEM_URL.format(story_id)
    if requests:
        try:
            response = requests.get(url, timeout=10)
            response.raise_for_status()
            return response.json()
        except Exception:
            return None
    else:
        try:
            with urllib.request.urlopen(url, timeout=10) as resp:
                return json.loads(resp.read().decode())
        except Exception:
            return None

def filter_by_keywords(title: str, keywords: List[str]) -> List[str]:
    """Check if title contains any keywords (case-insensitive)."""
    title_lower = title.lower()
    matches = []
    for keyword in keywords:
        if keyword.lower() in title_lower:
            matches.append(keyword)
    return matches

def get_score_emoji(score: int) -> str:
    """Return emoji based on score."""
    if score >= 500:
        return "🔥"
    elif score >= 200:
        return "⚡"
    elif score >= 100:
        return "📈"
    else:
        return "📊"

def format_digest(stories: List[Dict]) -> str:
    """Format stories into a readable digest."""
    date_str = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
    
    digest = f"""# 📰 HN Tech News Digest
**Generated: {date_str}**

Found {len(stories)} curated stories from HackerNews frontpage.

---

"""
    
    for i, story in enumerate(stories, 1):
        title = story.get('title', 'No title')
        url = story.get('url', f"https://news.ycombinator.com/item?id={story.get('id')}")
        score = story.get('score', 0)
        comments = story.get('descendants', 0)
        hn_link = f"https://news.ycombinator.com/item?id={story.get('id')}"
        matched_kw = ", ".join(story.get('matched_keywords', []))
        emoji = get_score_emoji(score)
        
        digest += f"""## {i}. {title}
{emoji} Score: **{score}** | 💬 Comments: **{comments}**
🔗 [Article]({url}) | [HN Discussion]({hn_link})
🏷️ Matched: *{matched_kw}*

---

"""
    
    digest += f"""
## Summary
- **Total Stories:** {len(stories)}
- **Top Keywords Found:** {', '.join(get_top_keywords(stories)[:10])}
- **Generated by:** HN News Digest Agent
"""
    return digest

def get_top_keywords(stories: List[Dict]) -> List[str]:
    """Get most common matched keywords."""
    from collections import Counter
    all_kw = []
    for story in stories:
        all_kw.extend(story.get('matched_keywords', []))
    return [kw for kw, _ in Counter(all_kw).most_common(15)]

def main():
    """Main entry point."""
    print("📰 HN News Digest Agent starting...")
    print(f"Fetching top 30 stories from HN API...")
    
    story_ids = fetch_hn_top_stories(limit=30)
    print(f"Got {len(story_ids)} story IDs")
    
    filtered_stories = []
    for story_id in story_ids:
        story = fetch_story_details(story_id)
        if story and 'title' in story:
            matched = filter_by_keywords(story['title'], KEYWORDS)
            if matched:
                story['matched_keywords'] = matched
                filtered_stories.append(story)
                print(f"  ✓ [{story.get('score', 0)}pts] {story['title'][:60]}...")
    
    # Sort by score descending
    filtered_stories.sort(key=lambda x: x.get('score', 0), reverse=True)
    
    digest = format_digest(filtered_stories)
    
    # Save digest
    output_file = "/root/hn-digest.md"
    with open(output_file, 'w') as f:
        f.write(digest)
    print(f"\n✅ Digest saved to {output_file}")
    print(f"📊 Total filtered stories: {len(filtered_stories)}")
    
    return digest

if __name__ == "__main__":
    main()
